#!/bin/sh
#
# $Id: $
#
version=$(cat conf-version)

verbose=0
while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
	;;
    *) optarg=
	;;
    esac

    case "$1" in
    --verbose)
	verbose=1
    ;;
    --clean)
	clean="--clean"
    ;;
    --release=*)
	release=$optarg
    ;;
    *)
    echo "invalid option [$1]"
    read key
    usage 1
    ;;
    esac

    shift
done

if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi

copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s wiringpi.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 0
fi

if [ $copy_src -eq 1 ] ; then
	if [ ! -d ../stage ] ; then
		mkdir ../stage
	fi
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	# /usr/local/src
	cd ..
	echo "Preparing wiringPi-"$version""
	/bin/cp -rp wiringPi-"$version" stage/wiringPi-"$version"
	# /usr/local/src/stage/wiringPi-$version
	cd stage/wiringPi-$version
	echo "Cleaning wiringPi-"$version""
	make -s clean >/dev/null 2>&1
	make -s distclean >/dev/null 2>&1
	/bin/rm -rf autom4te.cache .deps src/config.log
	# /usr/local/src/stage/
	cd ..
	echo "Archiving wiringPi-"$version".tar.gz in `pwd`"
	tar \
		--exclude="wiringPi-$version/.git" \
		--exclude="wiringPi-$version/debian"  \
		-cf - wiringPi-"$version" \
		| gzip -c > $rpmbuild/SOURCES/wiringPi-"$version".tar.gz
	/bin/rm -rf wiringPi-"$version"
fi

dist=`uname -r |cut -d . -f4`
if [ -z "$release" ] ; then
	if [ -f /usr/bin/gpio ] ; then
		mdist=$(rpm -qf /usr/bin/gpio|cut -d- -f3|cut -d. -f3)
		if [ " $dist" = " $mdist" ] ; then
			mversion=$(rpm -qf /usr/bin/gpio|cut -d- -f2)
			if [ "$mversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/gpio | cut -d- -f3 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi

# /usr/local/src/
cd ..
echo -n "Build RPM for wiringPi-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat wiringPi-$version/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		cd wiringPi-$version
		echo 1.$release > conf-release
		make -s wiringpi.spec
		cp wiringpi.spec /tmp
		make -C debian -s
		cd ../..
	else
		cp wiringPi-$version/wiringpi.spec /tmp
	fi
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	if [ $verbose -eq 0 ] ; then
		echo "rpmbuild -ba $clean --quiet /tmp/wiringpi.spec"
		rpmbuild -ba $clean --quiet /tmp/wiringpi.spec
	else
		echo "rpmbuild -ba $clean --quiet /tmp/wiringpi.spec"
		rpmbuild -ba $clean /tmp/wiringpi.spec
	fi
	if [ $? -eq 0 ] ; then
		/bin/rm /tmp/wiringpi.spec
		rpm --addsign \
			$rpmbuild/RPMS/$build_arch/wiringPi-"$version"-1."$release".$dist.$build_arch.rpm \
			$rpmbuild/RPMS/$build_arch/libwiringpi-"$version"-1."$release".$dist.$build_arch.rpm \
			$rpmbuild/RPMS/$build_arch/libwiringpi-devel-"$version"-1."$release".$dist.$build_arch.rpm \
			$rpmbuild/RPMS/$build_arch/libwiringpidev-"$version"-1."$release".$dist.$build_arch.rpm \
			$rpmbuild/RPMS/$build_arch/libwiringpidev-devel-"$version"-1."$release".$dist.$build_arch.rpm
		echo -n "RPM lint for wiringPi-"$version"-1."$release" (Y/N) - "
		read key
		if [ " $key" = " Y" -o " $key" = " y" ] ; then
			(
			for i in wiringPi libwiringpi libwiringpi-devel libwiringpidev libwiringpidev-devel
			do
				echo $i
				rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
			done
			echo wiringPi-"$version"-"1.$release".$dist.src.rpm
			rpmlint $rpmbuild/SRPMS/wiringPi-"$version"-"1.$release".$dist.src.rpm
			echo ------------------------
			) 2>&1 | less
		fi
	else
		/bin/rm /tmp/wiringPi.spec
	fi
else
	/bin/rm -rf /tmp/wiringPi-"$version"
fi

if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		/bin/rm -f $rpmbuild/SOURCES/wiringPi-"$version".tar.gz
	fi
fi
