#!/bin/sh
if [ ! -f /etc/debian_version ] ; then
	echo "Not a debian or ubuntu distribution" 1>&2
	exit 1
fi
make -s -C debian
wiringPi_version=$(cat conf-version)
echo "Cleaning Stage"
/bin/rm -rf $HOME/stage/WiringPi
echo "Copying Stage"
mkdir -p    $HOME/stage/WiringPi-$wiringPi_Version
cp -rp .    $HOME/stage/WiringPi-$wiringPi_Version
cd          $HOME/stage/WiringPi-$wiringPi_Version
dpkg-buildpackage -tc -b
if [ $? -eq 0 ] ; then
	/bin/rm -rf $HOME/stage/WiringPi-$wiringPi_Version
	ls -lt $HOME/stage
fi
